name: Closed Issue

on:
  issues:
    types: [closed]

jobs:
  light:
    runs-on: ubuntu-latest
    env:
      LIFX_TOKEN: ${{ secrets.LIFX_PAT }}
      LIFX_BULB_ID: ${{ secrets.LIFX_BULB_ID }}
      
    steps:
      - uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: green
          period: 5
