name: Closed Issue

on:
  issues:
    types: [closed]

jobs:
  light:
    runs-on: ubuntu-latest

    steps:
      - uses: lannonbr/lifx-trigger-action@1.0.0
        with:
          color: "#00ff00"
          period: 5
